name: AutoCR

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  autocr:
    name: autocr
    runs-on: ubuntu-latest
    steps:
      - name: Download Code Notes
        uses: actions/download-artifact@v4
        with:
          name: notes-json
      
      - name: Download Achievement and Leaderboard Code
        uses: actions/download-artifact@v4
        with:
          name: user-text
      
      - name: Download Rich Presence
        uses: actions/download-artifact@v4
        with:
          name: rich-text