name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: write

jobs:
  autocr:
    name: AutoCR
    runs-on: ubuntu-latest
    steps:
      - name: Audit Monster Max RAScript
        uses: joshraphael/rascript-audit@1dd2bd25f657aee4eb2cf18db15b27cbd0a270c9
        with:
          id: monstermax
          game-id: 4111
          rascript: 4111.rascript
          report: true
          severity: error
  publish:
    needs: autocr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Audit
        uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ls -R
