name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  compile:
    name: compile
    runs-on: ubuntu-latest
    env:
      RATOOLS_VERSION: v1.15.0
      RALIBRETRO_DIR: ~/Installs/RALibretro-x64 # same as Makefile
      DOTNET_ROOT_X64: C:\\Programs\\dotnet
      DOTNET_ROOT: C:\\Programs\\dotnet
      WINEPATH: C:\\Programs\\dotnet
      RA_CONNECT_TOKEN: ${{ secrets.RA_CONNECT_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.0'

      - name: Set ENV vars for github
        run: echo "RATOOLS_DIR=~/Installs/RATools-${{env.RATOOLS_VERSION}}" >> $GITHUB_ENV # same as Makefile

      - name: Create folders
        run: mkdir -p ${{env.RATOOLS_DIR}} && mkdir -p ${{env.RALIBRETRO_DIR}}/RACache/Data

      - name: Install wine
        run: sudo apt-get update && sudo apt-get install -y wine

      - name: Set Winecfg
        run: winecfg /v win10

      - name: Get RATools CLI
        run: wget -O ${{env.RATOOLS_DIR}}/RATools-${{env.RATOOLS_VERSION}}.zip "https://github.com/Jamiras/RATools/releases/download/${{env.RATOOLS_VERSION}}/RATools-${{env.RATOOLS_VERSION}}.zip"

      - name: Unpack RATools
        run: unzip ${{env.RATOOLS_DIR}}/RATools-${{env.RATOOLS_VERSION}}.zip -d ${{env.RATOOLS_DIR}}

      - name: Get .NET SDK 6.0.428
        run: bash .github/dotnet-sdk.sh
      
      - name: Get Code Notes
        run: make notes
      
      - name: Compile Code
        run: make compile
      
      - name: Upload Code Notes
        uses: actions/upload-artifact@v4
        with:
          name: notes-json
          path: ${{env.RALIBRETRO_DIR}}/RACache/Data/4111-Notes.json
      
      - name: Upload Achievement and Leaderboard Code
        uses: actions/upload-artifact@v4
        with:
          name: user-text
          path: ${{env.RALIBRETRO_DIR}}/RACache/Data/4111-User.txt
      
      - name: Upload Rich Presence
        uses: actions/upload-artifact@v4
        with:
          name: rich-text
          path: ${{env.RALIBRETRO_DIR}}/RACache/Data/4111-Rich.txt

  autocr:
    name: AutoCR
    needs: compile
    runs-on: ubuntu-latest
    env:
      GAME_ID: 4111
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: joshraphael/autocr-cli

      - name: Download Code Notes
        uses: actions/download-artifact@v4
        with:
          name: notes-json
      
      - name: Download Achievement and Leaderboard Code
        uses: actions/download-artifact@v4
        with:
          name: user-text
      
      - name: Download Rich Presence
        uses: actions/download-artifact@v4
        with:
          name: rich-text
      
      - name: Run AutoCR
        run: ./index.js --notes ${{env.GAME_ID}}-Notes.json --user ${{env.GAME_ID}}-User.txt --rich ${{env.GAME_ID}}-Rich.txt --severity error